#!/usr/bin/env bash
# Default safe header for any script generated by Hermes (spec 3.2).
set -Eeuo pipefail
IFS=$'\n\t'

trap 'echo "Command failed at line $LINENO" >&2' ERR

# Shell safety rules:
# - Prefer `timeout` for potentially long commands.
# - Prefer `--dry-run` where available.
# - Prefer non-interactive commands.
# - Avoid `eval` unless strictly necessary.
# - Avoid piping remote scripts into shell (curl | sh, wget | sh).
# - Avoid `sudo` unless explicitly approved.
# - Avoid `rm -rf` unless scoped, reviewed, and confirmed.
#
# Example safe command patterns:
#   timeout 60 git status --short --branch
#   timeout 120 npm ci
#   timeout 300 npm run test -- --runInBand
